export const entity = {
  VISIT: "VISIT",
  APPOINTMENT: "APPOINTMENT",
  STAFF: "STAFF",
  UNITS: "UNITS",
  SPECIALIZATION: "SPECIALIZATION",
  MEDICINE: "MEDICINE",
  SERVICE_TYPE: "SERVICE_TYPE",
  CLINIC_SCHEDULE: "CLINIC_SCHEDULE",
  DOCTOR_SCHEDULE: "DOCTOR_SCHEDULE",
  DOCTOR_HOLIDAY: "DOCTOR_HOLIDAY",
  DOCTOR: "DOCTOR",
  USER_STATUSES: "USER_STATUSES",
  COMPANY: "COMPANY",
  INSURANCE_PLAN: "INSURANCE_PLAN",
  INSURANCE_CLAIM: "INSURANCE_CLAIM",
} as const;

export type Entity = keyof typeof entity;
